import React, { createContext, useState, useCallback, ReactNode } from 'react';

type TranslationMessages = {
  [key: string]: string | TranslationMessages;
};

const translations: { [key: string]: TranslationMessages } = {
  en: {
    header: { home: 'Home', products: 'Products', about: 'About Us', contact: 'Contact', login: 'Login', register: 'Register', myAccount: 'My Account', logout: 'Logout', wishlist: 'Wishlist', cart: 'Cart', searchPlaceholder: 'Search products...', vouchers: 'Vouchers', orderHistory: 'Order History' },
    footer: { tagline: 'Preserving Nusantara\'s ancestral heritage with authentic heirlooms, spiritual media, and herbal remedies.', shopTitle: 'Shop', shopProducts: 'All Products', shopAbout: 'About Us', shopContact: 'Contact Us', helpTitle: 'Help', helpPrivacy: 'Privacy Policy', helpTerms: 'Terms of Service', helpFAQ: 'FAQ', socialTitle: 'Follow Us', socialTagline: 'Connect with us on social media.', copyright: 'All Rights Reserved' },
    toasts: { adminAccessDenied: 'Admin access required.', loginToAdd: 'Please log in to add items to cart.', itemAddedToCart: '{{name}} added to cart!', itemRemovedFromCart: '{{name}} removed from cart.', loginToWishlist: 'Please log in to use wishlist.', itemRemovedFromWishlist: 'Item removed from wishlist.', itemAddedToWishlist: 'Item added to wishlist!', welcome: 'Welcome back, {{name}}!', loginFailed: 'Incorrect email or password.', logoutSuccess: 'Successfully logged out.', emailExists: 'An account with this email already exists.', registerSuccess: 'Registration successful! Welcome.', voucherClaimed: 'Voucher {{code}} successfully claimed!', loginToClaim: 'Please log in to claim vouchers.' },
    home: { categoryKeilmuanTitle: "Spiritual Science", categoryKeilmuanDesc: "Explore ancient knowledge and spiritual practices for inner strength and wisdom.", categoryMediaBertuahTitle: "Empowered Media & Heirlooms", categoryMediaBertuahDesc: "Discover heirlooms and items imbued with special energies for protection and luck.", categoryMediaHerbalTitle: "Herbal Media & Remedies", categoryMediaHerbalDesc: "Natural remedies and herbal concoctions blessed for wellness and aura cleansing.", testimonial1: "The keris I got is truly authentic. The energy is amazing. Highly recommended!", testimonial2: "Tapak Pamungkas is a trusted source for spiritual items and heirlooms.", testimonial3: "I feel more connected to my cultural roots through the items I purchased here.", heroWelcome: "Welcome to", heroTitle: "Tapak Pamungkas", heroSubtitle: "Center for Authentic Empowered Items, Ancient Keris, Spiritual Services & Nusantara Wisdom", heroButton: "Explore Collection", categoriesTitle: "Our Product Categories", recommendationsTitle: "Featured Products", testimonialsTitle: "What Our Customers Say", viewAllProducts: "See All Products", ctaTitle: "Join Our Community", ctaSubtitle: "Get updates on new arrivals, exclusive offers, and stories from Nusantara heritage.", ctaPlaceholder: "Enter your email address", ctaButton: "Subscribe" },
    about: { title: "About Tapak Pamungkas", subtitle: "Guardians of Nusantara's Mystical & Spiritual Heritage", aboutUsTitle: "Our Story", aboutUsContent: "Tapak Pamungkas was born from a deep passion for Indonesian spiritual and cultural heritage. We are dedicated to offering authentic heirlooms, empowered items, and spiritual services with honesty, quality, and professionalism.", visionTitle: "Our Vision", visionContent: "To be the most trusted global source for authentic Nusantara heritage and spiritual items.", missionTitle: "Our Mission", missionItem1: "Curate and provide authentic, high-quality spiritual items.", missionItem2: "Educate on the history and significance of our cultural heritage.", missionItem3: "Support local artisans and spiritual practitioners.", missionItem4: "Foster a community passionate about Nusantara's traditions." },
    contact: { title: 'Contact Us', subtitle: 'Get in touch with us for inquiries, consultations, or order details.' },
    cart: { title: "Shopping Cart", empty: "Your cart is currently empty.", remove: "Remove", quantity: "Qty: {{count}}", summaryTitle: "Order Summary", subtotal: "Subtotal", shipping: "Shipping", shippingFree: "Free", total: "Total", checkoutButton: "Proceed to Checkout" },
    allProducts: { title: "Our Collection", subtitle: "Explore our curated selection of heirlooms and spiritual items.", noProducts: "No products found matching your criteria.", showingResultsFor: 'Showing results for: "{{query}}"', clearSearch: 'Clear Search' },
    wishlist: { title: "My Wishlist", subtitle: "Your saved items.", empty: "Your wishlist is empty.", startShopping: "Start Exploring" },
    vouchers: { title: "Vouchers & Discounts", subtitle: "Special offers just for you. Claim them now and use at checkout!", empty: "No vouchers available at the moment.", claimButton: "Claim", claimedButton: "Claimed", storeWide: "For all products", productSpecific: "Only for: {{productName}}", expiresOn: "Expires on: {{date}}" },
    login: { errorIncorrect: "Incorrect email or password.", errorAdminAccess: "Access denied to admin panel.", adminTitle: "Admin Portal", title: "Welcome Back", adminSubtitle: "Please enter your administrator credentials.", subtitle: "Log in to continue shopping.", emailLabel: "Email Address", passwordLabel: "Password", loginButton: "Login", noAccount: "Don't have an account?", registerLink: "Sign up" },
    register: { errorPasswordLength: "Password must be at least 6 characters long.", errorGeneral: "Registration failed. Please try again.", title: "Create an Account", subtitle: "Join our community and begin exploring.", nameLabel: "Full Name", emailLabel: "Email Address", passwordLabel: "Password", registerButton: "Sign Up", hasAccount: "Already have an account?", loginLink: "Log in" },
    checkout: { guideTitle: "How to Complete Your Order", step1Title: "Shipping Info", step1Desc: "Enter your delivery address and contact details", step2Title: "Apply Voucher (Optional)", step2Desc: "Enter voucher code to get a discount", step3Title: "Choose Payment", step3Desc: "Select Bank Transfer or QRIS", step4Title: "Place Order", step4Desc: "Review and confirm your order", voucherErrorProductSpecific: "This voucher is not valid for items in your cart.", voucherSuccess: "Voucher '{{code}}' applied successfully!", voucherError: "Invalid or expired voucher code.", alertFillShipping: "Please fill in all shipping details.", alertUploadProof: "Please upload proof of payment.", backToCart: "Back to Cart", title: "Checkout", shippingTitle: "Shipping Details", labelName: "Full Name", labelPhone: "Phone Number", labelAddress: "Full Address", labelCity: "City", labelPostalCode: "Postal Code", voucherTitle: "Voucher Code", voucherPlaceholder: "Enter voucher code", voucherApplyButton: "Apply", paymentTitle: "Payment Method", paymentBank: "Bank Transfer", paymentBankInstruction: "Please transfer to one of the following accounts:", paymentTotal: "Total Amount", paymentUploadLabel: "Upload Payment Proof", paymentCOD: "Cash on Delivery (COD)", discount: "Discount", confirmButton: "Place Order" },
    orderConfirmation: { title: "Thank You!", subtitle: "Your order has been placed successfully.", orderNumberLabel: "Order Number:", nextSteps: "We will contact you shortly to process your order and shipping.", backButton: "Back to Home" },
    productDetail: { notFound: "Product not found.", backToCart: "Back to Cart", backButton: "Back to Catalog", stockAvailable: "Stock Available", outOfStock: "Out of Stock", relatedProducts: "Related Products", recommendations: "You Might Also Like" },
    orderHistory: { title: "My Order History", subtitle: "Track your past purchases and shipping status.", empty: "You have not placed any orders yet.", startShopping: "Start Shopping", colId: "Order ID", colDate: "Date", colTotal: "Total", colStatus: "Status", colActions: "Actions", viewDetails: "View Details" },
    admin: { title: 'Admin Panel', modalCancel: 'Cancel', modalSave: 'Save Changes', deleteConfirm: 'Delete', modalEdit: 'Edit', modalAdd: 'Add New', deleteTitle: 'Confirm Deletion', deleteMessage: 'Are you sure you want to delete this item?', nav: { dashboard: 'Dashboard', products: 'Products', orders: 'Orders', users: 'Users', vouchers: 'Vouchers', logout: 'Logout' }, dashboard: { title: 'Dashboard', period: 'Period', last7Days: 'Last 7 Days', allTime: 'All Time', totalRevenue: 'Total Revenue', totalOrders: 'Total Orders', totalUsers: 'Total Users', totalProducts: 'Total Products' }, products: { title: 'Manage Products', addProduct: 'Add Product', colName: 'Name', colPrice: 'Price', colStock: 'Stock', colActions: 'Actions', formName: 'Product Name', formDescription: 'Description', formPrice: 'Price (IDR)', formStock: 'Stock Quantity', formSelectCategory: 'Select Category', formImageUrls: 'Image URLs', formImageUrl: 'Image URL {{number}}' }, users: { title: 'Manage Users', addUser: 'Add User', colName: 'Name', colEmail: 'Email', colRole: 'Role', colActions: 'Actions', roleAdmin: 'Admin', roleCustomer: 'Customer', formName: 'Full Name', formEmail: 'Email Address' }, orders: { title: 'Manage Orders', colId: 'Order ID', colCustomer: 'Customer', colTotal: 'Total', colStatus: 'Status', colActions: 'Actions' }, vouchers: { title: 'Manage Vouchers', addVoucher: 'Add Voucher', colCode: 'Code', colDiscount: 'Discount (%)', colExpiry: 'Expiry Date', colActions: 'Actions', formCode: 'Voucher Code', formDiscount: 'Discount (%)', formExpiry: 'Expiry Date' }, modalTitle: { product: 'Product', user: 'User', voucher: 'Voucher' } },
    categories: { semua: "Semua", keilmuan: "Keilmuan", mediabertuah: "Media Bertuah", mediaherbal: "Media Herbal" },
    productCard: { price: 'Harga', added: 'Ditambahkan', addToCart: 'Tambah Ke Keranjang' },
    filters: { filtersTitle: "Filter Produk", sortBy: "Urutkan Berdasarkan", default: "Default", priceLowHigh: "Harga: Rendah ke Tinggi", priceHighLow: "Harga: Tinggi ke Rendah", nameAZ: "Nama: A-Z", nameZA: "Nama: Z-A", newest: "Terbaru", priceRange: "Rentang Harga", minPrice: "Min", maxPrice: "Maks", apply: "Terapkan", resetFilters: "Reset Filter" },
  },
  id: {
    header: { home: 'Beranda', products: 'Produk', about: 'Tentang Kami', contact: 'Kontak', login: 'Masuk', register: 'Daftar', myAccount: 'Akun Saya', logout: 'Keluar', wishlist: 'Wishlist', cart: 'Keranjang', searchPlaceholder: 'Cari produk...', vouchers: 'Kupon', orderHistory: 'Riwayat Pesanan' },
    footer: { tagline: 'Melestarikan warisan leluhur Nusantara melalui koleksi keris pusaka, benda bertuah, dan keilmuan terpercaya.', shopTitle: 'Koleksi', shopProducts: 'Semua Produk', shopAbout: 'Tentang Kami', shopContact: 'Hubungi Kami', helpTitle: 'Bantuan', helpPrivacy: 'Kebijakan Privasi', helpTerms: 'Syarat & Ketentuan', helpFAQ: 'Pertanyaan Umum', socialTitle: 'Ikuti Kami', socialTagline: 'Terhubung dengan kami melalui media sosial.', copyright: 'Hak Cipta Dilindungi' },
    toasts: { adminAccessDenied: 'Akses admin diperlukan.', loginToAdd: 'Silakan masuk untuk menambahkan item ke keranjang.', itemAddedToCart: '{{name}} ditambahkan ke keranjang!', itemRemovedFromCart: '{{name}} dihapus dari keranjang.', loginToWishlist: 'Silakan masuk untuk menggunakan wishlist.', itemRemovedFromWishlist: 'Item dihapus dari wishlist.', itemAddedToWishlist: 'Item ditambahkan ke wishlist!', welcome: 'Selamat datang kembali, {{name}}!', loginFailed: 'Email atau kata sandi salah.', logoutSuccess: 'Anda berhasil keluar.', emailExists: 'Akun dengan email ini sudah ada.', registerSuccess: 'Pendaftaran berhasil! Selamat datang.', voucherClaimed: 'Kupon {{code}} berhasil diklaim!', loginToClaim: 'Silakan masuk untuk klaim kupon.' },
    home: { categoryKeilmuanTitle: "Keilmuan Spiritual", categoryKeilmuanDesc: "Kumpulan bimbingan keilmuan dan amalan spiritual nusantara yang terpercaya.", categoryMediaBertuahTitle: "Benda Bertuah & Keris Pusaka", categoryMediaBertuahDesc: "Koleksi keris pusaka sepuh dan benda bertuah dengan jaminan keaslian.", categoryMediaHerbalTitle: "Herbal & Sarana Ruwatan", categoryMediaHerbalDesc: "Ramuan herbal alami dan sarana ruwatan untuk perawatan dan pembersihan energi.", testimonial1: "Keris pusaka yang saya beli sangat bagus dan asli. Pengiriman cepat dan aman!", testimonial2: "Tapak Pamungkas adalah tempat terpercaya untuk produk spiritual dan benda bertuah.", testimonial3: "Pelayanan sangat baik dan ramah. Barang sampai dengan selamat dan sesuai foto.", heroWelcome: "Selamat Datang di", heroTitle: "Tapak Pamungkas", heroSubtitle: "Pusat Benda Bertuah, Keris Pusaka, Layanan Spiritual & Herbal Nusantara", heroButton: "Jelajahi Koleksi Pusaka", categoriesTitle: "Kategori Produk", recommendationsTitle: "Produk Pilihan Unggulan", testimonialsTitle: "Pengalaman Pembeli", viewAllProducts: "Lihat Semua Produk", ctaTitle: "Bergabung Dengan Kami", ctaSubtitle: "Dapatkan info produk terbaru, penawaran khusus, dan wawasan seputar warisan nusantara.", ctaPlaceholder: "Masukkan alamat email Anda", ctaButton: "Berlangganan" },
    about: { title: "Tentang Tapak Pamungkas", subtitle: "Pusat Warisan Budaya & Benda Bertuah Nusantara", aboutUsTitle: "Kisah Kami", aboutUsContent: "Tapak Pamungkas hadir sebagai wadah terpercaya untuk memaharkan keris pusaka, benda bertuah, serta layanan spiritual dan keilmuan Nusantara. Kami berkomitmen menjaga keaslian, kualitas, serta memberikan pelayanan yang amanah dan profesional.", visionTitle: "Visi Kami", visionContent: "Menjadi pusat terpercaya untuk produk spiritual dan pusaka Nusantara bagi para kolektor dan peminat budaya.", missionTitle: "Misi Kami", missionItem1: "Menyediakan keris pusaka dan benda bertuah yang asli dan berkualitas.", missionItem2: "Memberikan bimbingan dan pelayanan yang ramah serta amanah.", missionItem3: "Mendukung kelestarian pengrajin dan kebudayaan tradisional.", missionItem4: "Membangun hubungan baik dan saling percaya dengan seluruh pembeli." },
    contact: { title: 'Hubungi Kami', subtitle: 'Silakan hubungi kami untuk konsultasi, pertanyaan produk, atau informasi pesanan.' },
    cart: { title: "Keranjang Belanja", empty: "Keranjang belanja Anda saat ini kosong.", remove: "Hapus", quantity: "Jml: {{count}}", summaryTitle: "Ringkasan Pesanan", subtotal: "Subtotal", shipping: "Pengiriman", shippingFree: "Gratis", total: "Total Pembayaran", checkoutButton: "Lanjut ke Pembayaran" },
    allProducts: { title: "Katalog Produk", subtitle: "Jelajahi seluruh koleksi keris pusaka, benda bertuah, dan ramuan herbal kami.", noProducts: "Tidak ada produk yang sesuai dengan pencarian Anda.", showingResultsFor: 'Menampilkan hasil pencarian untuk: "{{query}}"', clearSearch: 'Hapus Pencarian' },
    wishlist: { title: "Wishlist Saya", subtitle: "Daftar produk simpanan favorit Anda.", empty: "Wishlist Anda masih kosong.", startShopping: "Mulai Belanja" },
    vouchers: { title: "Kupon Diskon", subtitle: "Gunakan kupon diskon khusus untuk pembelian produk pilihan Anda.", empty: "Belum ada kupon promo yang tersedia saat ini.", claimButton: "Klaim Kupon", claimedButton: "Sudah Diklaim", storeWide: "Berlaku untuk semua produk", productSpecific: "Khusus produk: {{productName}}", expiresOn: "Berlaku hingga: {{date}}" },
    login: { errorIncorrect: "Email atau kata sandi salah.", errorAdminAccess: "Akses khusus admin.", adminTitle: "Portal Admin", title: "Selamat Datang Kembali", adminSubtitle: "Silakan masukkan akun admin Anda.", subtitle: "Masuk untuk melanjutkan pembelian Anda.", emailLabel: "Alamat Email", passwordLabel: "Kata Sandi", loginButton: "Masuk", noAccount: "Belum punya akun?", registerLink: "Daftar sekarang" },
    register: { errorPasswordLength: "Kata sandi minimal 6 karakter.", errorGeneral: "Pendaftaran gagal. Silakan coba lagi.", title: "Buat Akun Baru", subtitle: "Bergabunglah untuk mulai berbelanja dan mendapatkan penawaran.", nameLabel: "Nama Lengkap", emailLabel: "Alamat Email", passwordLabel: "Kata Sandi", registerButton: "Daftar", hasAccount: "Sudah punya akun?", loginLink: "Masuk" },
    checkout: { guideTitle: "Cara Menyelesaikan Pesanan", step1Title: "Informasi Pengiriman", step1Desc: "Isi alamat pengiriman dan nomor telepon Anda", step2Title: "Kupon Diskon (Opsional)", step2Desc: "Masukkan kode kupon jika ada untuk mendapatkan diskon", step3Title: "Metode Pembayaran", step3Desc: "Pilih Transfer Bank atau QRIS", step4Title: "Buat Pesanan", step4Desc: "Periksa kembali detail pesanan Anda lalu konfirmasi", voucherErrorProductSpecific: "Kupon ini tidak berlaku untuk produk di keranjang Anda.", voucherSuccess: "Kupon '{{code}}' berhasil digunakan!", voucherError: "Kode kupon tidak valid atau sudah kedaluwarsa.", alertFillShipping: "Harap isi semua detail pengiriman.", alertUploadProof: "Harap unggah bukti pembayaran.", backToCart: "Kembali ke Keranjang", title: "Checkout", shippingTitle: "Alamat & Data Pengiriman", labelName: "Nama Lengkap Penerima", labelPhone: "Nomor WhatsApp / HP", labelAddress: "Alamat Lengkap", labelCity: "Kota / Kabupaten", labelPostalCode: "Kode Pos", voucherTitle: "Kode Kupon Diskon", voucherPlaceholder: "Masukkan kode kupon", voucherApplyButton: "Gunakan", paymentTitle: "Pilihan Pembayaran", paymentBank: "Transfer Bank", paymentBankInstruction: "Silakan transfer ke salah satu rekening berikut:", paymentTotal: "Total Pembayaran", paymentUploadLabel: "Unggah Bukti Transfer", paymentCOD: "Bayar di Tempat (COD)", discount: "Diskon Kupon", confirmButton: "Konfirmasi & Buat Pesanan" },
    orderConfirmation: { title: "Terima Kasih!", subtitle: "Pesanan Anda telah berhasil dibuat.", orderNumberLabel: "Nomor Pesanan:", nextSteps: "Tim kami akan segera menghubungi Anda untuk memproses pesanan dan pengiriman.", backButton: "Kembali ke Beranda" },
    productDetail: { notFound: "Produk tidak ditemukan.", backToCart: "Kembali ke Keranjang", backButton: "Kembali ke Katalog", stockAvailable: "Stok Tersedia", outOfStock: "Stok Habis", relatedProducts: "Produk Serupa", recommendations: "Rekomendasi Lainnya" },
    orderHistory: { title: "Riwayat Pesanan Saya", subtitle: "Lacak status pesanan dan pengiriman barang Anda.", empty: "Anda belum pernah melakukan pemesanan.", startShopping: "Mulai Belanja", colId: "ID Pesanan", colDate: "Tanggal", colTotal: "Total", colStatus: "Status", colActions: "Aksi", viewDetails: "Lihat Detail" },
    admin: { title: 'Admin Panel', modalCancel: 'Batal', modalSave: 'Simpan', deleteConfirm: 'Hapus', modalEdit: 'Ubah', modalAdd: 'Tambah Baru', deleteTitle: 'Konfirmasi Penghapusan', deleteMessage: 'Apakah Anda yakin ingin menghapus data ini?', nav: { dashboard: 'Dasbor', products: 'Produk', orders: 'Pesanan', users: 'Pengguna', vouchers: 'Kupon', logout: 'Keluar' }, dashboard: { title: 'Ringkasan Dasbor', period: 'Periode', last7Days: '7 Hari Terakhir', allTime: 'Semua Waktu', totalRevenue: 'Total Pendapatan', totalOrders: 'Total Pesanan', totalUsers: 'Total Pelanggan', totalProducts: 'Total Produk' }, products: { title: 'Kelola Produk & Stok', addProduct: 'Tambah Produk Baru', colName: 'Nama Produk', colPrice: 'Harga', colStock: 'Stok', colActions: 'Aksi', formName: 'Nama Produk', formDescription: 'Deskripsi', formPrice: 'Harga (IDR)', formStock: 'Jumlah Stok', formSelectCategory: 'Pilih Kategori', formImageUrls: 'URL Foto', formImageUrl: 'URL Foto {{number}}' }, users: { title: 'Kelola Pengguna', addUser: 'Tambah Pengguna', colName: 'Nama', colEmail: 'Email', colRole: 'Peran', colActions: 'Aksi', roleAdmin: 'Admin', roleCustomer: 'Pelanggan', formName: 'Nama Lengkap', formEmail: 'Alamat Email' }, orders: { title: 'Kelola Pesanan & Pembayaran', colId: 'ID Pesanan', colCustomer: 'Pelanggan', colTotal: 'Total', colStatus: 'Status', colActions: 'Aksi' }, vouchers: { title: 'Kelola Kupon Promo', addVoucher: 'Tambah Kupon Baru', colCode: 'Kode Kupon', colDiscount: 'Diskon (%)', colExpiry: 'Tanggal Kedaluwarsa', colActions: 'Aksi', formCode: 'Kode Kupon', formDiscount: 'Diskon (%)', formExpiry: 'Tanggal Kedaluwarsa' }, modalTitle: { product: 'Produk', user: 'Pengguna', voucher: 'Kupon' } },
    categories: { semua: "Semua", keilmuan: "Keilmuan Spiritual", mediabertuah: "Benda Bertuah & Keris", mediaherbal: "Herbal & Ruwatan" },
    productCard: { price: 'Harga', added: 'Ditambahkan', addToCart: 'Tambah Ke Keranjang' },
    filters: { filtersTitle: "Filter Produk", sortBy: "Urutkan Berdasarkan", default: "Default", priceLowHigh: "Harga: Rendah ke Tinggi", priceHighLow: "Harga: Tinggi ke Rendah", nameAZ: "Nama: A-Z", nameZA: "Nama: Z-A", newest: "Terbaru", priceRange: "Rentang Harga", minPrice: "Min", maxPrice: "Maks", apply: "Terapkan", resetFilters: "Reset Filter" },
  }
};

type Locale = 'en' | 'id';

interface LocaleContextType {
  locale: Locale;
  setLocale: (locale: Locale) => void;
  t: (key: string, params?: { [key: string]: string | number }) => string;
}

const defaultContextValue: LocaleContextType = {
  locale: 'id',
  setLocale: () => console.warn('setLocale called outside of a LocaleProvider'),
  t: (key: string) => key,
};

export const LocaleContext = createContext<LocaleContextType>(defaultContextValue);

const getNestedTranslation = (messages: TranslationMessages, key: string): string | undefined => {
  const keys = key.split('.');
  let result: any = messages;
  for (const k of keys) {
    result = result?.[k];
    if (result === undefined) return undefined;
  }
  return typeof result === 'string' ? result : undefined;
}

export const LocaleProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [locale, setLocale] = useState<Locale>('id');

  const t = useCallback((key: string, params?: { [key: string]: string | number }) => {
    const langMessages = translations[locale] || translations.id;
    let message = getNestedTranslation(langMessages, key);

    if (message === undefined) {
      const fallbackMessages = translations.en;
      message = getNestedTranslation(fallbackMessages, key);
      if (message === undefined) {
        console.warn(`Translation key "${key}" not found in locale "${locale}" or fallback "en".`);
        return key;
      }
    }

    if (params) {
      Object.keys(params).forEach(pKey => {
        message = message!.replace(`{{${pKey}}}`, String(params[pKey]));
      });
    }

    return message;
  }, [locale]);

  return (
    <LocaleContext.Provider value={{ locale, setLocale, t }}>
      {children}
    </LocaleContext.Provider>
  );
};